version: '3.8'

services:
  mysql: 
    image: mysql
    container_name: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_PASSWORD = $MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD = $MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE = $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT    
    # volumes:
    #   - ./mysql:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app